### ISSUE TITLE
Short Title field and tooltip on Page editing screen

### ISSUE THREAD

**Issue by nepa** [foliovision/fv-all-in-one-seo-pack#4]
When I **un**check the 'Add Short Title Attribute field to post editing screen' option, the input field is hidden from the **post** editing screen, but it is still visible on the **page** editing screen. I'd expect it to be hidden there, too.

Furthermore, the tooltip for 'Short title | Menu Label' on the page editing screen seems broken. It has several whitespace characters before the actual text begins.

![seo options for pages](https://cloud.githubusercontent.com/assets/772192/8267994/b9ba9e2e-1775-11e5-8576-08b88eb0a069.png)

**Comment by foliovision** [comment]
Hello nepa,

thank you for the bug report!

1) The short title will keep appearing for pages as it's used as a menu label. This is an older feature from before WP nav menus were introduced, but it's still important.

2) The whitespace bug was fixed in version 1.6.27 released just now.

Thanks,
Martin
